services:

  mysql:
    image: mysql:8.0
    container_name: parking-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smart_parking_db
    networks:
      - parking-network
    restart: unless-stopped

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    volumes:
      - ./config-repo:/config-repo
    environment:
      SPRING_PROFILES_ACTIVE: native
      SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS: file:/config-repo
    networks:
      - parking-network
    restart: on-failure
    depends_on:
      - mysql

  service-registry:
    build: ./service-registry
    container_name: service-registry
    ports:
      - "8761:8761"
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
      EUREKA_CLIENT_FETCH_REGISTRY: "false"
    depends_on:
      - config-server
    networks:
      - parking-network
    restart: on-failure

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
    depends_on:
      - config-server
      - service-registry
      - mysql
    restart: on-failure
    networks:
      - parking-network

  vehicle-service:
    build: ./vehicle-service
    container_name: vehicle-service
    ports:
      - "8082:8082"
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
    depends_on:
      - config-server
      - service-registry
      - mysql
    restart: on-failure
    networks:
      - parking-network

  parking-space-service:
    build: ./parking-space-service
    container_name: parking-space-service
    ports:
      - "8083:8083"
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
    depends_on:
      - config-server
      - service-registry
      - mysql
    restart: on-failure
    networks:
      - parking-network

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8084:8084"
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
    depends_on:
      - config-server
      - service-registry
      - mysql
    restart: on-failure
    networks:
      - parking-network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
    depends_on:
      - config-server
      - service-registry
    restart: on-failure
    networks:
      - parking-network

networks:
  parking-network:
    driver: bridge