server:
  port: 8084

spring:
  application:
    name: payment-service

  config:
    import: optional:configserver:http://config-server:8888

  # Docker MySQL Database Configurations
  datasource:
    url: jdbc:mysql://parking-mysql:3306/smart_parking_db?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    prefer-ip-address: true