spring.application.name=parking-space-service
server.port=8083

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.datasource.url=jdbc:mysql://localhost:3306/parking_db?createDatabaseIfNotExist=true
spring.datasource.username=Dis@2002
spring.datasource.password=Dis@2002

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true